apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployvia
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - applications/status
      - applicationsets
      - applicationsets/status
    verbs:
      - get
      - list
      - watch
