apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployvia
  labels:
    app.kubernetes.io/name: deployvia
    app.kubernetes.io/part-of: deployvia
    app.kubernetes.io/component: controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: deployvia
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: deployvia
    spec:
      containers:
        - image: ghcr.io/3lvia/deployvia:latest
          imagePullPolicy: Always
          env:
            - name: GIN_MODE
              value: release
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 30
          name: deployvia
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 30
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      serviceAccountName: deployvia
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsUser: 1001
        supplementalGroups:
          - 1001
