apiVersion: v1
kind: Service
metadata:
  name: deployvia
  labels:
    app.kubernetes.io/name: deployvia
    app.kubernetes.io/part-of: deployvia
    app.kubernetes.io/component: controller
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: deployvia
