apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: deployvia
    app.kubernetes.io/part-of: deployvia
    app.kubernetes.io/component: controller
  name: deployvia
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - applications/status
      - applicationsets
      - applicationsets/status
    verbs:
      - get
      - list
      - watch
